### ISSUE TITLE
HA Cluster provider support 

### ISSUE THREAD

**Issue by alishavez7** [Azure/AMS-Migration#30]
Hi Team,

Any plan to roll out the support of HA Cluster provider migration in the provided migration script from AMS Classic to new one.

**Comment by mohitmakhija1** [comment]
Hi,
Currently, we do not have plans for adding migration for HA Cluster providers, please create them manually from the azure portal, let us know in case you are facing any problems.

Below link has the list of steps to follow while setting up the provider
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-ha-cluster-azure-monitor-sap-solutions

Also, ensure that you create a provider for both the nodes of your HA cluster.

Thanks.

**Comment by mohitmakhija1** [comment]
Please re-open this issue of raise a ticket on azure portal in case more assistance is needed.
